import type { Actor, ActorType } from "@aaspai/contracts";
import { IDENTITY_PROTOCOL_VERSION } from "@aaspai/contracts/identity";

/**
 * Create a new Actor with the given properties. The ID must be
 * generated by the caller (typically a UUID).
 */
export function createActor(input: {
  id: string;
  type: ActorType;
  organizationId: string;
  displayName?: string;
  metadata?: Record<string, unknown>;
}): Actor {
  return {
    protocolVersion: IDENTITY_PROTOCOL_VERSION,
    id: input.id,
    type: input.type,
    organizationId: input.organizationId,
    displayName: input.displayName,
    createdAt: new Date().toISOString(),
    metadata: input.metadata,
  };
}

/**
 * Human-readable label for an actor type.
 */
export function actorTypeLabel(type: ActorType): string {
  const labels: Record<ActorType, string> = {
    human: "Human User",
    agent: "AI Agent",
    service: "Service Account",
    system: "System",
    team: "Team",
  };
  return labels[type];
}
