/**
 * AI-observer telemetry migrations.
 *
 * The telemetry storage model adapts the AI Observer reference schema
 * (flat tables with JSON columns) and adds Aaspai tenant ownership.
 * Every telemetry row carries `organization_id`; indexes are
 * org-leading to match real queries.
 *
 * The DDL is written to be valid on both SQLite and PostgreSQL:
 * timestamps and JSON payloads are stored as TEXT, booleans as INTEGER
 * (0/1), and ids as TEXT. Statements are idempotent so `runMigrations`
 * can be re-run safely on every process start.
 */

const TELEMETRY_TABLES = [
  `CREATE TABLE IF NOT EXISTS telemetry_logs (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    received_at TEXT NOT NULL,
    provider TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    service_name TEXT,
    event_name TEXT,
    body TEXT NOT NULL DEFAULT '',
    severity_text TEXT,
    severity_number INTEGER,
    session_id TEXT,
    execution_id TEXT,
    attempt_id TEXT,
    trace_id TEXT,
    span_id TEXT,
    model TEXT,
    operation TEXT,
    tool_name TEXT,
    actor_id TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    resource_attributes_json TEXT NOT NULL DEFAULT '{}',
    scope_name TEXT,
    scope_version TEXT,
    raw_json TEXT,
    raw_available INTEGER NOT NULL DEFAULT 0,
    redaction_metadata_json TEXT,
    dedup_key TEXT,
    import_source TEXT,
    import_offset INTEGER,
    import_hash TEXT,
    parse_status TEXT NOT NULL DEFAULT 'ok',
    parse_error TEXT,
    source_path TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_spans (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    received_at TEXT NOT NULL,
    provider TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    service_name TEXT,
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    parent_span_id TEXT,
    name TEXT NOT NULL,
    kind TEXT,
    status TEXT NOT NULL DEFAULT 'unset',
    status_message TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT,
    duration_ns INTEGER,
    session_id TEXT,
    execution_id TEXT,
    attempt_id TEXT,
    model TEXT,
    operation TEXT,
    actor_id TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    resource_attributes_json TEXT NOT NULL DEFAULT '{}',
    scope_name TEXT,
    scope_version TEXT,
    events_json TEXT NOT NULL DEFAULT '[]',
    links_json TEXT NOT NULL DEFAULT '[]',
    raw_json TEXT,
    raw_available INTEGER NOT NULL DEFAULT 0,
    dedup_key TEXT,
    import_source TEXT,
    import_offset INTEGER,
    import_hash TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_metrics (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    start_time TEXT,
    received_at TEXT NOT NULL,
    provider TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    service_name TEXT,
    name TEXT NOT NULL,
    description TEXT,
    unit TEXT,
    metric_type TEXT NOT NULL,
    session_id TEXT,
    execution_id TEXT,
    attempt_id TEXT,
    model TEXT,
    actor_id TEXT,
    aggregation_temporality INTEGER,
    is_monotonic INTEGER,
    value REAL,
    count INTEGER,
    sum REAL,
    min REAL,
    max REAL,
    bucket_counts_json TEXT,
    explicit_bounds_json TEXT,
    scale INTEGER,
    zero_count INTEGER,
    positive_offset INTEGER,
    positive_bucket_counts_json TEXT,
    negative_offset INTEGER,
    negative_bucket_counts_json TEXT,
    quantile_values_json TEXT,
    quantile_quantiles_json TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    resource_attributes_json TEXT NOT NULL DEFAULT '{}',
    scope_name TEXT,
    scope_version TEXT,
    raw_json TEXT,
    raw_available INTEGER NOT NULL DEFAULT 0,
    dedup_key TEXT,
    import_source TEXT,
    import_offset INTEGER,
    import_hash TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_sessions (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    session_id TEXT NOT NULL,
    first_seen_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    status TEXT,
    model TEXT,
    user_id TEXT,
    execution_ids_json TEXT NOT NULL DEFAULT '[]',
    attempt_ids_json TEXT NOT NULL DEFAULT '[]',
    trace_ids_json TEXT NOT NULL DEFAULT '[]',
    message_count INTEGER NOT NULL DEFAULT 0,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    usage_json TEXT,
    cost_usd REAL,
    cost_is_estimate INTEGER NOT NULL DEFAULT 0,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    schema_version INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_session_messages (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    ts TEXT NOT NULL,
    role TEXT NOT NULL,
    kind TEXT NOT NULL,
    text TEXT,
    tool_name TEXT,
    tool_input_json TEXT,
    tool_result_json TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    raw_json TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_import_state (
    organization_id TEXT NOT NULL,
    source TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_hash TEXT NOT NULL,
    imported_at TEXT NOT NULL,
    record_count INTEGER NOT NULL DEFAULT 0,
    byte_offset INTEGER NOT NULL DEFAULT 0,
    message_count INTEGER NOT NULL DEFAULT 0,
    parser_state_json TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    last_error TEXT,
    PRIMARY KEY (organization_id, source, file_path)
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_ingest_errors (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    kind TEXT NOT NULL,
    message TEXT NOT NULL,
    raw_json TEXT,
    record_count INTEGER NOT NULL DEFAULT 0,
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_dashboards (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_default INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_dashboard_widgets (
    id TEXT PRIMARY KEY,
    dashboard_id TEXT NOT NULL REFERENCES telemetry_dashboards(id) ON DELETE CASCADE,
    widget_type TEXT NOT NULL,
    title TEXT NOT NULL,
    grid_column INTEGER NOT NULL,
    grid_row INTEGER NOT NULL,
    col_span INTEGER NOT NULL DEFAULT 1,
    row_span INTEGER NOT NULL DEFAULT 1,
    config_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS telemetry_live_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id TEXT NOT NULL,
    type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
];

const TELEMETRY_INDEXES = [
  `CREATE INDEX IF NOT EXISTS tl_org_observed_idx ON telemetry_logs(organization_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tl_org_session_idx ON telemetry_logs(organization_id, session_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tl_org_execution_idx ON telemetry_logs(organization_id, execution_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tl_org_trace_idx ON telemetry_logs(organization_id, trace_id)`,
  `CREATE INDEX IF NOT EXISTS tl_org_provider_model_idx ON telemetry_logs(organization_id, provider, model, observed_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tl_org_dedup_key_uniq ON telemetry_logs(organization_id, dedup_key)`,
  `CREATE INDEX IF NOT EXISTS ts_org_trace_idx ON telemetry_spans(organization_id, trace_id, observed_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ts_org_span_uniq ON telemetry_spans(organization_id, trace_id, span_id)`,
  `CREATE INDEX IF NOT EXISTS ts_org_observed_idx ON telemetry_spans(organization_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS ts_org_session_idx ON telemetry_spans(organization_id, session_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tm_org_observed_idx ON telemetry_metrics(organization_id, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tm_org_name_idx ON telemetry_metrics(organization_id, name, observed_at)`,
  `CREATE INDEX IF NOT EXISTS tm_org_service_idx ON telemetry_metrics(organization_id, service_name, observed_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tsess_org_session_uniq ON telemetry_sessions(organization_id, session_id)`,
  `CREATE INDEX IF NOT EXISTS tsess_org_last_seen_idx ON telemetry_sessions(organization_id, last_seen_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tmsg_session_seq_uniq ON telemetry_session_messages(organization_id, session_id, seq)`,
  `CREATE INDEX IF NOT EXISTS tmsg_session_idx ON telemetry_session_messages(organization_id, session_id, seq)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS timport_org_source_path_uniq ON telemetry_import_state(organization_id, source, file_path)`,
  `CREATE INDEX IF NOT EXISTS timport_org_source_idx ON telemetry_import_state(organization_id, source)`,
  `CREATE INDEX IF NOT EXISTS terr_org_ts_idx ON telemetry_ingest_errors(organization_id, ts)`,
  `CREATE INDEX IF NOT EXISTS tdash_org_idx ON telemetry_dashboards(organization_id)`,
  `CREATE INDEX IF NOT EXISTS twidget_dashboard_idx ON telemetry_dashboard_widgets(dashboard_id, grid_column, grid_row)`,
  `CREATE INDEX IF NOT EXISTS tlive_org_id_idx ON telemetry_live_events(organization_id, id)`,
];

export const TELEMETRY_MIGRATION_STATEMENTS = [...TELEMETRY_TABLES, ...TELEMETRY_INDEXES];
