import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";

/**
 * Phase 2 schema — SQLite (foundation slice).
 *
 * The same logical schema works on Postgres; the only difference is
 * the column types and the index syntax. The Postgres variant is
 * generated by drizzle-kit and lives alongside this file.
 *
 * Foundation slice is SQLite-only. Postgres support lands in Phase 4.
 */

// ─── loops ─────────────────────────────────────────────────────────
export const loops = sqliteTable("loops", {
  id: text("id").primaryKey(),                           // "loop/<slug>"
  organizationId: text("organization_id").notNull(),
  patternId: text("pattern_id").notNull(),
  configJson: text("config_json").notNull().default("{}"),
  gateJson: text("gate_json").notNull().default("{}"),
  budgetJson: text("budget_json").notNull().default("{}"),
  scheduleJson: text("schedule_json").notNull().default("{}"),
  paused: integer("paused", { mode: "boolean" }).notNull().default(false),
  pauseReason: text("pause_reason"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => ({
  orgIdx: index("loops_org_idx").on(t.organizationId),
  patternIdx: index("loops_pattern_idx").on(t.organizationId, t.patternId),
}));

// ─── wakeups ───────────────────────────────────────────────────────
export const wakeups = sqliteTable("wakeups", {
  id: text("id").primaryKey(),                           // "wake_<uuid>"
  organizationId: text("organization_id").notNull(),
  loopId: text("loop_id").notNull().references(() => loops.id),
  source: text("source").notNull(),                      // timer | assignment | routine | on_demand | continuation | manual
  triggerDetail: text("trigger_detail"),
  reason: text("reason"),
  agentId: text("agent_id"),
  payloadJson: text("payload_json").notNull().default("{}"),
  status: text("status").notNull().default("queued"),    // queued | claimed | coalesced | completed | failed | skipped | cancelled
  coalescedIntoWakeupId: text("coalesced_into_wakeup_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  requestedAt: text("requested_at").notNull(),
  requestedByActorId: text("requested_by_actor_id"),
  requestedByActorType: text("requested_by_actor_type"), // user | agent | system
  claimedAt: text("claimed_at"),
  finishedAt: text("finished_at"),
  sessionId: text("session_id"),
  error: text("error"),
}, (t) => ({
  loopIdx: index("wakeups_loop_idx").on(t.loopId),
  orgRequestedIdx: index("wakeups_org_requested_idx").on(t.organizationId, t.requestedAt),
  statusIdx: index("wakeups_status_idx").on(t.status),
  idemUniq: uniqueIndex("wakeups_idem_uniq").on(t.idempotencyKey),
}));

// ─── sessions ─────────────────────────────────────────────────────
export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),                           // "sess_<uuid>"
  organizationId: text("organization_id").notNull(),
  wakeupId: text("wakeup_id").notNull().references(() => wakeups.id),
  agentId: text("agent_id").notNull(),
  adapter: text("adapter").notNull(),
  runtimeJson: text("runtime_json").notNull().default("{}"),
  prompt: text("prompt").notNull(),
  configJson: text("config_json").notNull().default("{}"),
  status: text("status").notNull().default("queued"),
  sessionId: text("session_id"),
  sessionParamsJson: text("session_params_json"),
  sessionDisplayId: text("session_display_id"),
  resultJson: text("result_json"),
  usageJson: text("usage_json"),
  costUsd: real("cost_usd"),
  errorFamily: text("error_family"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  pendingQuestionJson: text("pending_question_json"),
  startedAt: text("started_at"),
  finishedAt: text("finished_at"),
  durationMs: integer("duration_ms"),
  parentSessionId: text("parent_session_id"),
}, (t) => ({
  wakeupIdx: index("sessions_wakeup_idx").on(t.wakeupId),
  agentStatusIdx: index("sessions_agent_status_idx").on(t.agentId, t.status),
  orgFinishedIdx: index("sessions_org_finished_idx").on(t.organizationId, t.finishedAt),
}));

// ─── session_events ───────────────────────────────────────────────
export const sessionEvents = sqliteTable("session_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sessionId: text("session_id").notNull().references(() => sessions.id, { onDelete: "cascade" }),
  ts: text("ts").notNull(),
  kind: text("kind").notNull(),
  payloadJson: text("payload_json").notNull(),
  seq: integer("seq").notNull(),
}, (t) => ({
  sessionSeqUniq: uniqueIndex("session_events_session_seq_uniq").on(t.sessionId, t.seq),
  sessionIdx: index("session_events_session_idx").on(t.sessionId, t.seq),
}));

// ─── budget_ledger ────────────────────────────────────────────────
export const budgetLedger = sqliteTable("budget_ledger", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  organizationId: text("organization_id").notNull(),
  scope: text("scope").notNull(),                       // loop | agent | org
  scopeId: text("scope_id").notNull(),
  window: text("window").notNull(),                      // YYYY-MM-DD | YYYY-MM | run_<id>
  tokensUsed: integer("tokens_used").notNull().default(0),
  costUsd: real("cost_usd").notNull().default(0),
  runs: integer("runs").notNull().default(1),
  ts: text("ts").notNull(),
}, (t) => ({
  scopeWindowIdx: index("budget_ledger_scope_window_idx").on(t.scope, t.scopeId, t.window),
  orgIdx: index("budget_ledger_org_idx").on(t.organizationId),
}));

// ─── audit_events ─────────────────────────────────────────────────
export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  actorId: text("actor_id").notNull(),
  action: text("action").notNull(),
  targetType: text("target_type").notNull(),
  targetId: text("target_id"),
  correlationId: text("correlation_id"),
  occurredAt: text("occurred_at").notNull(),
  recordedAt: text("recorded_at").notNull(),
  metadataJson: text("metadata_json"),
}, (t) => ({
  orgTimeIdx: index("audit_events_org_time_idx").on(t.organizationId, t.occurredAt),
  actionIdx: index("audit_events_action_idx").on(t.action),
  targetIdx: index("audit_events_target_idx").on(t.targetType, t.targetId),
}));

export type LoopRow = typeof loops.$inferSelect;
export type LoopInsert = typeof loops.$inferInsert;
export type WakeupRow = typeof wakeups.$inferSelect;
export type WakeupInsert = typeof wakeups.$inferInsert;
export type SessionRow = typeof sessions.$inferSelect;
export type SessionInsert = typeof sessions.$inferInsert;
export type SessionEventRow = typeof sessionEvents.$inferSelect;
export type SessionEventInsert = typeof sessionEvents.$inferInsert;
export type BudgetLedgerRow = typeof budgetLedger.$inferSelect;
export type BudgetLedgerInsert = typeof budgetLedger.$inferInsert;
export type AuditEventRow = typeof auditEvents.$inferSelect;
export type AuditEventInsert = typeof auditEvents.$inferInsert;
